name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of Image"
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image for pushed tag
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          push: true
          tags: |
            ghcr.io/snippetors/snippets:${GITHUB_REF##*/}
            ghcr.io/snippetors/snippets:latest
      - name: Build container image for workflow_dispatch
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          push: true
          tags: |
            ghcr.io/snippetors/snippets:${{ github.event.inputs.tag }}
