name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Increment "major", "minor", "patch", or "pre*" version; or specify version'
        default: patch
        required: true

jobs:
  build:
    name: Release, Build, and Push Docker image to GitHub Packages
    strategy:
      matrix:
        node: ["14"]

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install conventional-changelog-cli
        run: npm install --global conventional-changelog-cli

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release
        id: release_tag
        run: echo "::set-output name=IMAGE_TAG::$(npm version ${{ github.event.inputs.version }} | tail -1)"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/snippetors/snippets

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/snippetors/snippets:${{ steps.release_tag.outputs.IMAGE_TAG }}
            ghcr.io/snippetors/snippets:latest
