name: Go Test

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/snippets/go/**
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.17"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint
        working-directory: docs/snippets/go
        run: go vet ./...
      - name: Test
        working-directory: docs/snippets/go
        run: go test ./...
