name: Release Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Increment "major", "minor", "patch", or "pre*" version; or specify version'
        default: patch
        required: true
      plugin:
        description: 'Plugin, "tabs" or "code-copy"'
        required: true


jobs:
  release_it:
    strategy:
      matrix:
        node: ["14"]

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Input Validation
        run: |
          if [[ ! " tabs code-copy " =~ " ${{ github.event.inputs.plugin }} " ]]; then
              echo "The plugin must be one of [tabs, code-copy]"
              exit -1
          fi

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install release-it
        run: npm install --global release-it

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release
        working-directory: packages/@snippetors/vuepress-plugin-${{ github.event.inputs.plugin }}
        run: release-it -- ${{ github.event.inputs.version }} --ci
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
